package org.name.model.domain.movie;

import java.util.UUID;

public interface Entity {

  /**
   * Returns the id generated by neo4J. This id may be reused if the entity is deleted in the
   * database.
   *
   * @return
   */
  public Long getId();

  /**
   * Returns the id generated by the application. This id is not reused if an entity is deleted in
   * the database.
   *
   * @return
   */
  public UUID getUuid();
}
